[tool.poetry]
name = "flaskr-k8s"
version = "0.1.0"
description = ""
authors = ["Jim Cooley <jim@cooley.io>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
